from app.providers.detection.base import LanguageDetectionProvider
from app.providers.detection.lingua import LinguaLanguageDetectionProvider
from app.providers.detection.mock import MockLanguageDetectionProvider
